### ISSUE TITLE
Can't deploy to github pages

### ISSUE THREAD

**Issue by ganyariya** [yrpang/github-actions-hexo#2]
Hello, I happended to error, such that cannot deploy to github pages.

I use two repositories

1. ganariya.github.io
2. ganariya_blog(private)

and ganariya_blog is the hexo repository and deploy  to ganariya.github.io.

And I'd like to use github-actions-hexo, so
I make ssh and set public-key in ganariya.github.io and 
I set private-key as DEPLOY_KEY in ganariya_blog.

But, actions happens error

```
2019-12-27T12:40:23.5083253Z ##[group]Run yrpang/github-actions-hexo@master
2019-12-27T12:40:23.5083845Z with:
2019-12-27T12:40:23.5090460Z   deploykey: ***

2019-12-27T12:40:23.5090997Z   username: Ganariya
2019-12-27T12:40:23.5092159Z   email: willwill1997willwill@yahoo.co.jp
2019-12-27T12:40:23.5092693Z   if_update_files: false
2019-12-27T12:40:23.5093211Z   branch: master
2019-12-27T12:40:23.5093721Z   if_update_cloudflare: false
2019-12-27T12:40:23.5094231Z ##[endgroup]
2019-12-27T12:40:23.5138153Z ##[command]/usr/bin/docker run --name ee6d39f9bc3dca347fcb1f699254ef090be_ccf700 --label 671ee6 --workdir /github/workspace --rm -e INPUT_DEPLOYKEY -e INPUT_USERNAME -e INPUT_EMAIL -e INPUT_IF_UPDATE_FILES -e INPUT_GITHUB_TOKEN -e INPUT_BRANCH -e INPUT_IF_UPDATE_CLOUDFLARE -e INPUT_CLOUDFLARE_API_KEY -e INPUT_CLOUDFLARE_ZONE -e INPUT_CLOUDFLARE_USERNAME -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/ganariya_blog/ganariya_blog":"/github/workspace" 671ee6:d39f9bc3dca347fcb1f699254ef090be
2019-12-27T12:40:23.8516811Z # github.com:22 SSH-2.0-babeld-778045a0
2019-12-27T12:40:27.8393868Z /usr/local/bin/hexo -> /usr/local/lib/node_modules/hexo-cli/bin/hexo
2019-12-27T12:40:27.8671392Z npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/hexo-cli/node_modules/fsevents):
2019-12-27T12:40:27.8673090Z npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2019-12-27T12:40:27.8678795Z 
2019-12-27T12:40:27.8689553Z + hexo-cli@3.1.0
2019-12-27T12:40:27.8690056Z added 82 packages from 356 contributors in 3.421s
2019-12-27T12:40:35.5742560Z 
2019-12-27T12:40:35.5743898Z > ejs@2.7.4 postinstall /github/workspace/node_modules/ejs
2019-12-27T12:40:35.5744911Z > node ./postinstall.js
2019-12-27T12:40:35.5745370Z 
2019-12-27T12:40:35.6237811Z Thank you for installing [35mEJS[0m: built with the [32mJake[0m JavaScript build tool ([32mhttps://jakejs.com/[0m)
2019-12-27T12:40:35.6239080Z 
2019-12-27T12:40:36.1355735Z npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/nunjucks/node_modules/fsevents):
2019-12-27T12:40:36.1422650Z npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2019-12-27T12:40:36.1432862Z npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
2019-12-27T12:40:36.1443853Z npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2019-12-27T12:40:36.1453324Z 
2019-12-27T12:40:36.1485454Z added 372 packages from 472 contributors and audited 2744 packages in 7.735s
2019-12-27T12:40:36.3534241Z 
2019-12-27T12:40:36.3535087Z 3 packages are looking for funding
2019-12-27T12:40:36.3535579Z   run `npm fund` for details
2019-12-27T12:40:36.3535821Z 
2019-12-27T12:40:36.3541392Z found 0 vulnerabilities
2019-12-27T12:40:36.3541852Z 
2019-12-27T12:40:37.5005101Z INFO  Start processing
2019-12-27T12:40:37.7538298Z INFO  Files loaded in 255 ms
2019-12-27T12:40:38.3423095Z INFO  Generated: index.html
2019-12-27T12:40:38.3453742Z INFO  Generated: archives/index.html
2019-12-27T12:40:38.3491178Z INFO  Generated: fancybox/blank.gif
2019-12-27T12:40:38.3491858Z INFO  Generated: fancybox/jquery.fancybox.css
2019-12-27T12:40:38.3492715Z INFO  Generated: fancybox/jquery.fancybox.js
2019-12-27T12:40:38.3493237Z INFO  Generated: fancybox/jquery.fancybox.pack.js
2019-12-27T12:40:38.3510033Z INFO  Generated: fancybox/fancybox_loading.gif
2019-12-27T12:40:38.3510605Z INFO  Generated: fancybox/fancybox_loading@2x.gif
2019-12-27T12:40:38.3511151Z INFO  Generated: fancybox/fancybox_sprite.png
2019-12-27T12:40:38.3521925Z INFO  Generated: archives/2019/12/index.html
2019-12-27T12:40:38.3523475Z INFO  Generated: tags/this-is-test/index.html
2019-12-27T12:40:38.3524043Z INFO  Generated: fancybox/fancybox_overlay.png
2019-12-27T12:40:38.3524601Z INFO  Generated: archives/2019/index.html
2019-12-27T12:40:38.3545440Z INFO  Generated: js/script.js
2019-12-27T12:40:38.3546520Z INFO  Generated: fancybox/helpers/jquery.fancybox-buttons.css
2019-12-27T12:40:38.3547088Z INFO  Generated: fancybox/fancybox_sprite@2x.png
2019-12-27T12:40:38.3547797Z INFO  Generated: fancybox/helpers/jquery.fancybox-buttons.js
2019-12-27T12:40:38.3548534Z INFO  Generated: fancybox/helpers/jquery.fancybox-media.js
2019-12-27T12:40:38.3549258Z INFO  Generated: fancybox/helpers/jquery.fancybox-thumbs.css
2019-12-27T12:40:38.3549992Z INFO  Generated: fancybox/helpers/jquery.fancybox-thumbs.js
2019-12-27T12:40:38.3556413Z INFO  Generated: css/fonts/FontAwesome.otf
2019-12-27T12:40:38.3562728Z INFO  Generated: css/fonts/fontawesome-webfont.svg
2019-12-27T12:40:38.3566874Z INFO  Generated: css/fonts/fontawesome-webfont.eot
2019-12-27T12:40:38.3571275Z INFO  Generated: css/fonts/fontawesome-webfont.woff
2019-12-27T12:40:38.3575593Z INFO  Generated: fancybox/helpers/fancybox_buttons.png
2019-12-27T12:40:38.3580630Z INFO  Generated: css/style.css
2019-12-27T12:40:38.3585134Z INFO  Generated: 2019/12/27/nyann/index.html
2019-12-27T12:40:38.3589397Z INFO  Generated: css/images/banner.jpg
2019-12-27T12:40:38.3595616Z INFO  Generated: 2019/12/27/sample-page/index.html
2019-12-27T12:40:38.3596397Z INFO  Generated: 2019/12/27/test-page/index.html
2019-12-27T12:40:38.3603455Z INFO  Generated: css/fonts/fontawesome-webfont.ttf
2019-12-27T12:40:38.3604256Z INFO  Generated: 2019/12/27/hello-world/index.html
2019-12-27T12:40:38.3611486Z INFO  32 files generated in 607 ms
2019-12-27T12:40:39.4254425Z INFO  Deploying: git
2019-12-27T12:40:39.4323274Z INFO  Setting up Git deployment...
2019-12-27T12:40:39.4424020Z Initialized empty Git repository in /github/workspace/.deploy_git/.git/
2019-12-27T12:40:39.4550148Z [master (root-commit) 2afa7ee] First commit
2019-12-27T12:40:39.4554373Z  1 file changed, 0 insertions(+), 0 deletions(-)
2019-12-27T12:40:39.4554967Z  create mode 100644 placeholder
2019-12-27T12:40:39.4564383Z INFO  Clearing .deploy_git folder...
2019-12-27T12:40:39.4589249Z INFO  Copying files from public folder...
2019-12-27T12:40:39.4749459Z INFO  Copying files from extend dirs...
2019-12-27T12:40:39.5326337Z [master 0a99d87] Site updated: 2019-12-27 12:40:39
2019-12-27T12:40:39.5353288Z  33 files changed, 7134 insertions(+)
2019-12-27T12:40:39.5354297Z  create mode 100644 2019/12/27/hello-world/index.html
2019-12-27T12:40:39.5354878Z  create mode 100644 2019/12/27/nyann/index.html
2019-12-27T12:40:39.5355665Z  create mode 100644 2019/12/27/sample-page/index.html
2019-12-27T12:40:39.5356571Z  create mode 100644 2019/12/27/test-page/index.html
2019-12-27T12:40:39.5357114Z  create mode 100644 archives/2019/12/index.html
2019-12-27T12:40:39.5357648Z  create mode 100644 archives/2019/index.html
2019-12-27T12:40:39.5358165Z  create mode 100644 archives/index.html
2019-12-27T12:40:39.5358689Z  create mode 100644 css/fonts/FontAwesome.otf
2019-12-27T12:40:39.5359583Z  create mode 100644 css/fonts/fontawesome-webfont.eot
2019-12-27T12:40:39.5360356Z  create mode 100644 css/fonts/fontawesome-webfont.svg
2019-12-27T12:40:39.5361118Z  create mode 100644 css/fonts/fontawesome-webfont.ttf
2019-12-27T12:40:39.5361857Z  create mode 100644 css/fonts/fontawesome-webfont.woff
2019-12-27T12:40:39.5362735Z  create mode 100644 css/images/banner.jpg
2019-12-27T12:40:39.5363273Z  create mode 100644 css/style.css
2019-12-27T12:40:39.5363766Z  create mode 100644 fancybox/blank.gif
2019-12-27T12:40:39.5364500Z  create mode 100644 fancybox/fancybox_loading.gif
2019-12-27T12:40:39.5365089Z  create mode 100644 fancybox/fancybox_loading@2x.gif
2019-12-27T12:40:39.5365722Z  create mode 100644 fancybox/fancybox_overlay.png
2019-12-27T12:40:39.5366270Z  create mode 100644 fancybox/fancybox_sprite.png
2019-12-27T12:40:39.5366807Z  create mode 100644 fancybox/fancybox_sprite@2x.png
2019-12-27T12:40:39.5367368Z  create mode 100644 fancybox/helpers/fancybox_buttons.png
2019-12-27T12:40:39.5368253Z  create mode 100644 fancybox/helpers/jquery.fancybox-buttons.css
2019-12-27T12:40:39.5369258Z  create mode 100644 fancybox/helpers/jquery.fancybox-buttons.js
2019-12-27T12:40:39.5370059Z  create mode 100644 fancybox/helpers/jquery.fancybox-media.js
2019-12-27T12:40:39.5371041Z  create mode 100644 fancybox/helpers/jquery.fancybox-thumbs.css
2019-12-27T12:40:39.5371804Z  create mode 100644 fancybox/helpers/jquery.fancybox-thumbs.js
2019-12-27T12:40:39.5372715Z  create mode 100644 fancybox/jquery.fancybox.css
2019-12-27T12:40:39.5373277Z  create mode 100644 fancybox/jquery.fancybox.js
2019-12-27T12:40:39.5373867Z  create mode 100644 fancybox/jquery.fancybox.pack.js
2019-12-27T12:40:39.5374419Z  create mode 100644 index.html
2019-12-27T12:40:39.5374931Z  create mode 100644 js/script.js
2019-12-27T12:40:39.5375573Z  delete mode 100644 placeholder
2019-12-27T12:40:39.5376314Z  create mode 100644 tags/this-is-test/index.html
2019-12-27T12:40:39.5757979Z fatal: could not read Username for 'https://github.com': No such device or address
2019-12-27T12:40:39.5780211Z FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
2019-12-27T12:40:39.5781413Z Error: Spawn failed
2019-12-27T12:40:39.5782332Z     at ChildProcess.<anonymous> (/github/workspace/node_modules/hexo-util/lib/spawn.js:51:21)
2019-12-27T12:40:39.5784993Z     at ChildProcess.emit (events.js:305:20)
2019-12-27T12:40:39.5785604Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
2019-12-27T12:40:40.9099113Z ##[error]Docker run failed with exit code 2
2019-12-27T12:40:40.9130840Z Cleaning up orphan processes
```

And my main.yml is 

```
name: Hexo Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}
      - uses: yrpang/github-actions-hexo@master
        with:
          deploykey: ${{secrets.DEPLOY_KEY}}
          username: "Ganariya"
          email: "willwill1997willwill@yahoo.co.jp"
```

I would you to give me some advice.

Sorry, for bad English, thank you.

**Comment by yrpang** [comment]
抱歉才看到…

我觉得可能是 "_config.yml"中的"Deployment"那部分配置有问题。

repo那部分需要使用[”SSH URLs“](https://help.github.com/en/github/using-git/which-remote-url-should-i-use)的格式也就是git@github.com/用户名/仓库地址 的格式。

下面是样例：

```
deploy:
  type: git
  repo: git@github.com:yrpang/yrpang.github.io.git
  branch: master
```

你可以先尝试一下，有问题欢迎再提问！

**Comment by ganyariya** [comment]
Hello, yrpang!

I fix the part such that below you said

```
deploy:
  type: git
  repo: git@github.com:yrpang/yrpang.github.io.git
  branch: master
```

it went well!

Thank you very much!
